# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
