# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
